[workspace]
members = [
    "crates/jellyswarrm-proxy",
    "crates/jellyswarrm-macros",
    "crates/jellyfin-api",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["lukaskreussel@gmail.com"]
repository = "https://github.com/LLukas22/Jellyswarrm"

[workspace.dependencies]
jellyswarrm-macros = { path = "crates/jellyswarrm-macros" }
# HTTP and Web Framework
axum = { version = "0.8", features = ["macros"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "gzip", "brotli", "deflate", "rustls-tls"]  }
moka = { version = "0.12.11", features = ["future"] }

# Database
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "chrono"] }

# Async Runtime
tokio = { version = "1.0", features = ["full"] }

# Logging and Tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tracing-appender = "0.2"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
url = {version = "2.4", features = ["serde"]}
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
sha2 = "0.10"
hex = "0.4"
rand = "0.8"

# Development dependencies
tokio-test = "0.4"
